### PR TITLE
make tls InsecureSkipVerify flag configurable

### PR DESCRIPTION
**Pull request by vladimirdulov**
ability to make InsecureSkipVerify flag configurable

### CODE REVIEW

**Comment by vladimirdulov** [comment]
Please add this patch to the lib so we can configure the InsecureSkipVerify flag in remark42 application further.

**Comment by umputun** [comment]
LGTM

@paskal - pls take a look just in case

**Review by paskal — APPROVED** [review]

**Comment by umputun** [comment]
@vladimirdulov still fails on linter

**Comment by vladimirdulov** [comment]
There were no errors on the recent linter version (1.55).
 
just updated it for linter v.1.50, it has passed with no errors locally now.

**Comment by vladimirdulov** [comment]
@umputun @paskal Could you please review it again. 
We are looking forward to start working on the packaging of remark42 for cloudron.io

**Pull request merged**
